# Generated by Django 4.2.17 on 2024-12-29 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph', models.FloatField()),
                ('elevation', models.FloatField()),
                ('slope', models.FloatField()),
                ('aspect', models.FloatField()),
                ('water_holding_capacity', models.FloatField()),
                ('solar_radiation', models.FloatField()),
                ('electrical_conductivity', models.FloatField()),
                ('zinc', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('predicted_crop', models.CharField(max_length=100)),
                ('water_requirement', models.FloatField()),
                ('irrigation_strategy', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
